Include demo host app inside the project
intesys/ymock pull request #1
Opened 2022-02-25 16:50 UTC by axelpezzo

2022-02-26 01:35 UTC, aditecco requested changes

2022-02-26 01:35 UTC, aditecco commented on package.json
> +    "mock": "copyfiles -u 1 static/mockServiceWorker.js dist",
I can't find this command in the source, the IDE errors out and the project won't start : (

```
sh: copyfiles: command not found
```

2022-02-26 01:35 UTC, aditecco commented on package.json
> +    "dev": "yarn run clean && npm run mock && parcel",
Can we handle all the scripts with `yarn`?

```suggestion
    "dev": "yarn run clean && yarn run mock && parcel",
```

2022-02-26 01:35 UTC, aditecco commented on package.json
> +    "dev": "yarn run clean && npm run mock && parcel",
To be consistent, we should also delete the package-lock in favor of yarn-lock

2022-02-26 01:36 UTC, aditecco commented
@axelpezzo Ciao Alex! : ) Ho iniziato la review

2022-02-28 09:28 UTC, axelpezzo commented on package.json
> +    "mock": "copyfiles -u 1 static/mockServiceWorker.js dist",
I used https://www.npmjs.com/package/copyfiles, that's a global librarys and I see only now that I didn'nt add it to the dependencies. Depsite that I think that I could switch from this library to a parcel's script. I will work on that asap.

2022-03-03 14:44 UTC, aditecco approved these changes

2022-03-03 14:45 UTC, merged